// ============================================
// CodeQuest — Theme Presets
// Pre-built theme configurations
// ============================================

import type { ThemePreset } from '@/types/theme';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    description: 'Deep dark with vibrant purple accents. The default CodeQuest experience.',
    preview: { background: '#0F0F14', accent: '#6C63FF', surface: '#1A1A24' },
    preferences: {
      colorMode: 'dark',
      accentColor: '#6C63FF',
      fontFamily: 'Inter',
      borderRadius: 'rounded',
      animationLevel: 'normal',
      density: 'comfortable',
    },
    isPremium: false,
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    description: 'Cool navy depths with bright blue highlights.',
    preview: { background: '#0F0F14', accent: '#3B82F6', surface: '#1A1A24' },
    preferences: {
      colorMode: 'dark',
      accentColor: '#3B82F6',
      fontFamily: 'Inter',
      borderRadius: 'rounded',
      animationLevel: 'normal',
      density: 'comfortable',
    },
    isPremium: false,
  },
  {
    id: 'emerald-night',
    name: 'Emerald Night',
    description: 'Nature-inspired dark theme with fresh green energy.',
    preview: { background: '#0F0F14', accent: '#22C55E', surface: '#1A1A24' },
    preferences: {
      colorMode: 'dark',
      accentColor: '#22C55E',
      fontFamily: 'Inter',
      borderRadius: 'rounded',
      animationLevel: 'normal',
      density: 'comfortable',
    },
    isPremium: false,
  },
  {
    id: 'sunset-amber',
    name: 'Sunset Amber',
    description: 'Warm amber glow for comfortable late-night coding.',
    preview: { background: '#0F0F14', accent: '#F59E0B', surface: '#1A1A24' },
    preferences: {
      colorMode: 'dark',
      accentColor: '#F59E0B',
      fontFamily: 'Inter',
      borderRadius: 'rounded',
      animationLevel: 'normal',
      density: 'comfortable',
    },
    isPremium: false,
  },
  {
    id: 'rose-garden',
    name: 'Rose Garden',
    description: 'Elegant rose-tinted dark theme with soft pink accents.',
    preview: { background: '#0F0F14', accent: '#F43F5E', surface: '#1A1A24' },
    preferences: {
      colorMode: 'dark',
      accentColor: '#F43F5E',
      fontFamily: 'Inter',
      borderRadius: 'pill',
      animationLevel: 'expressive',
      density: 'comfortable',
    },
    isPremium: false,
  },
  {
    id: 'light-classic',
    name: 'Light Classic',
    description: 'Clean, bright light mode for daytime productivity.',
    preview: { background: '#F8F9FC', accent: '#6C63FF', surface: '#FFFFFF' },
    preferences: {
      colorMode: 'light',
      accentColor: '#6C63FF',
      fontFamily: 'Inter',
      borderRadius: 'rounded',
      animationLevel: 'normal',
      density: 'comfortable',
    },
    isPremium: false,
  },
  {
    id: 'amoled-black',
    name: 'AMOLED Black',
    description: 'True black background for OLED screens. Maximum battery saving.',
    preview: { background: '#000000', accent: '#6C63FF', surface: '#0A0A0F' },
    preferences: {
      colorMode: 'amoled',
      accentColor: '#6C63FF',
      fontFamily: 'Inter',
      borderRadius: 'rounded',
      animationLevel: 'normal',
      density: 'comfortable',
    },
    isPremium: false,
  },
  // ── Premium Themes ────────────────────────
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    description: 'Futuristic cyberpunk aesthetics with neon cyan glow.',
    preview: { background: '#000000', accent: '#06B6D4', surface: '#0A0A0F' },
    preferences: {
      colorMode: 'amoled',
      accentColor: '#06B6D4',
      fontFamily: 'JetBrainsMono',
      borderRadius: 'sharp',
      animationLevel: 'expressive',
      density: 'compact',
    },
    isPremium: true,
  },
  {
    id: 'sakura-bloom',
    name: 'Sakura Bloom',
    description: 'Delicate cherry blossom pinks on a warm light background.',
    preview: { background: '#F8F9FC', accent: '#EC4899', surface: '#FFFFFF' },
    preferences: {
      colorMode: 'light',
      accentColor: '#EC4899',
      fontFamily: 'Nunito',
      borderRadius: 'pill',
      animationLevel: 'expressive',
      density: 'comfortable',
    },
    isPremium: true,
  },
  {
    id: 'monochrome-hacker',
    name: 'Monochrome Hacker',
    description: 'Classic terminal aesthetics. Green on black. Minimal and focused.',
    preview: { background: '#000000', accent: '#22C55E', surface: '#0A0A0F' },
    preferences: {
      colorMode: 'amoled',
      accentColor: '#22C55E',
      fontFamily: 'FiraCode',
      borderRadius: 'sharp',
      animationLevel: 'reduced',
      density: 'compact',
    },
    isPremium: true,
  },
];
